package Shared;

public enum ClientResponses {
		CHALLENGE, RTC, END, DECKLIST, 
		LOGIN, LOGOUT, DISCONNECT, ADMIN, 
		SAY, TELL, SELCARD, SELTEMPLATE, 
		CHOICE, ABILITY, PLAY, ATTACK, PASS,
		GETCOLLECTION, GETCARDINFO, CANCEL;
}
